spring.application.name=auth-service
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/instagram}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

user-service.url=http://localhost:8082

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.algorithm=HS256
jwt.issuer=instagram-auth-service

# Logging
logging.level.org.instagram.auth.security=DEBUG
logging.level.org.instagram.auth.controller=DEBUG