spring.application.name=api-gateway
server.port=8080

spring.autoconfigure.exclude=org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration,org.springframework.cloud.function.web.FunctionHandlerMapping

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.cloud.function.definition=
