spring.application.name=interaction-service
#Promeniti kasnije za sada je 82 a post je 81
server.port=8082

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/interaction_db
spring.datasource.username=rosu
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

post.service.url=http://localhost:8081

logging.level.com.instagram.interaction=DEBUG
logging.level.org.springframework.web=INFO