server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interactions_db
    username: rosu
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect