spring:
  application:
    name: feed-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/instagram}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

follow:
  service:
    url: ${FOLLOW_SERVICE_URL:http://follow-service:8080}

post:
  service:
    url: ${POST_SERVICE_URL:http://post-service:8080}

user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:8080}

block:
  service:
    url: ${BLOCK_SERVICE_URL:http://block-service:8080}

logging:
  level:
    root: INFO

